ignore:
  - vulnerability: CVE-2023-2650
    package:
      name: libssl3
      version: 3.1.0-r4

  - vulnerability: CVE-2023-2650
    package:
      name: libcrypto3
      version: 3.1.0-r4

  - vulnerability: CVE-2023-45853
    package:
      name: zlib
      version: 1.3.1-r2
